In [68]:
import pandas as pd
import numpy as np
import re

In [69]:
!head NST-EST2014-01.csv

In [70]:
pd.read_csv("NST-EST2014-01.csv").head()

,table with row headers in column A and column headers in rows 3 through 4. (leading dots indicate sub-parts),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Table 1. Annual Estimates of the Resident Popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geographic Area,"April 1, 2010",NaN,Population Estimate (as of July 1),NaN,NaN,NaN,NaN
2,NaN,Census,Estimates Base,2010,2011,2012,2013,2014
3,United States,"308,745,538","308,758,105","309,347,057","311,721,632","314,112,078","316,497,531","318,857,056"
4,Northeast,"55,317,240","55,318,348","55,381,690","55,635,670","55,832,038","56,028,220","56,152,333"

In [71]:
pd.read_csv("NST-EST2014-01.csv", skiprows=3).head()

,Unnamed: 0,Census,Estimates Base,2010,2011,2012,2013,2014
0,United States,"308,745,538","308,758,105","309,347,057","311,721,632","314,112,078","316,497,531","318,857,056"
1,Northeast,"55,317,240","55,318,348","55,381,690","55,635,670","55,832,038","56,028,220","56,152,333"
2,Midwest,"66,927,001","66,929,898","66,972,390","67,149,657","67,331,458","67,567,871","67,745,108"
3,South,"114,555,744","114,562,951","114,871,231","116,089,908","117,346,322","118,522,802","119,771,934"
4,West,"71,945,553","71,946,908","72,121,746","72,846,397","73,602,260","74,378,638","75,187,681"

In [72]:
pop_data = pd.read_csv("NST-EST2014-01.csv", skiprows=3)

In [73]:
pop_data = pop_data.rename(columns={"Unnamed: 0": "State"})

In [74]:
pop_data.head()

,State,Census,Estimates Base,2010,2011,2012,2013,2014
0,United States,"308,745,538","308,758,105","309,347,057","311,721,632","314,112,078","316,497,531","318,857,056"
1,Northeast,"55,317,240","55,318,348","55,381,690","55,635,670","55,832,038","56,028,220","56,152,333"
2,Midwest,"66,927,001","66,929,898","66,972,390","67,149,657","67,331,458","67,567,871","67,745,108"
3,South,"114,555,744","114,562,951","114,871,231","116,089,908","117,346,322","118,522,802","119,771,934"
4,West,"71,945,553","71,946,908","72,121,746","72,846,397","73,602,260","74,378,638","75,187,681"

In [75]:
pop_data.index = pop_data.pop("State")

In [76]:
pop_data.head()

,Census,Estimates Base,2010,2011,2012,2013,2014
State,,,,,,,
United States,"308,745,538","308,758,105","309,347,057","311,721,632","314,112,078","316,497,531","318,857,056"
Northeast,"55,317,240","55,318,348","55,381,690","55,635,670","55,832,038","56,028,220","56,152,333"
Midwest,"66,927,001","66,929,898","66,972,390","67,149,657","67,331,458","67,567,871","67,745,108"
South,"114,555,744","114,562,951","114,871,231","116,089,908","117,346,322","118,522,802","119,771,934"
West,"71,945,553","71,946,908","72,121,746","72,846,397","73,602,260","74,378,638","75,187,681"

In [77]:
pop_data

,Census,Estimates Base,2010,2011,2012,2013,2014
State,,,,,,,
United States,"308,745,538","308,758,105","309,347,057","311,721,632","314,112,078","316,497,531","318,857,056"
Northeast,"55,317,240","55,318,348","55,381,690","55,635,670","55,832,038","56,028,220","56,152,333"
Midwest,"66,927,001","66,929,898","66,972,390","67,149,657","67,331,458","67,567,871","67,745,108"
South,"114,555,744","114,562,951","114,871,231","116,089,908","117,346,322","118,522,802","119,771,934"
West,"71,945,553","71,946,908","72,121,746","72,846,397","73,602,260","74,378,638","75,187,681"
.Alabama,"4,779,736","4,780,127","4,785,822","4,801,695","4,817,484","4,833,996","4,849,377"
.Alaska,"710,231","710,249","713,856","722,572","731,081","737,259","736,732"
.Arizona,"6,392,017","6,392,310","6,411,999","6,472,867","6,556,236","6,634,997","6,731,484"
.Arkansas,"2,915,918","2,915,958","2,922,297","2,938,430","2,949,300","2,958,765","2,966,369"
.California,"37,253,956","37,254,503","37,336,011","37,701,901","38,062,780","38,431,393","38,802,500"
.Colorado,"5,029,196","5,029,324","5,048,575","5,119,661","5,191,709","5,272,086","5,355,866"
.Connecticut,"3,574,097","3,574,096","3,579,345","3,590,537","3,594,362","3,599,341","3,596,677"
.Delaware,"897,934","897,936","899,731","907,829","916,881","925,240","935,614"
.District of Columbia,"601,723","601,767","605,210","620,427","635,040","649,111","658,893"
.Florida,"18,801,310","18,804,623","18,852,220","19,107,900","19,355,257","19,600,311","19,893,297"
.Georgia,"9,687,653","9,688,681","9,714,464","9,813,201","9,919,000","9,994,759","10,097,343"
.Hawaii,"1,360,301","1,360,301","1,363,950","1,378,251","1,392,766","1,408,987","1,419,561"
.Idaho,"1,567,582","1,567,652","1,570,639","1,583,780","1,595,590","1,612,843","1,634,464"
.Illinois,"12,830,632","12,831,587","12,840,097","12,858,725","12,873,763","12,890,552","12,880,580"
.Indiana,"6,483,802","6,484,192","6,490,308","6,516,560","6,537,632","6,570,713","6,596,855"
.Iowa,"3,046,355","3,046,869","3,050,295","3,064,904","3,075,935","3,092,341","3,107,126"
.Kansas,"2,853,118","2,853,132","2,858,949","2,869,965","2,885,966","2,895,801","2,904,021"
.Kentucky,"4,339,367","4,339,349","4,349,838","4,370,038","4,383,465","4,399,583","4,413,457"
.Louisiana,"4,533,372","4,533,479","4,545,581","4,575,972","4,604,744","4,629,284","4,649,676"
.Maine,"1,328,361","1,328,361","1,327,361","1,327,930","1,328,592","1,328,702","1,330,089"
.Maryland,"5,773,552","5,773,785","5,788,101","5,843,833","5,891,819","5,938,737","5,976,407"
.Massachusetts,"6,547,629","6,547,817","6,564,073","6,612,270","6,655,829","6,708,874","6,745,408"
.Michigan,"9,883,640","9,884,133","9,876,498","9,875,736","9,884,781","9,898,193","9,909,877"
.Minnesota,"5,303,925","5,303,925","5,310,418","5,348,036","5,380,615","5,422,060","5,457,173"
.Mississippi,"2,967,297","2,968,103","2,970,811","2,978,464","2,986,137","2,992,206","2,994,079"
...,...,...,...,...,...,...,...
.Nevada,"2,700,551","2,700,692","2,703,493","2,718,586","2,755,245","2,791,494","2,839,099"
.New Hampshire,"1,316,470","1,316,466","1,316,517","1,318,109","1,321,297","1,322,616","1,326,813"
.New Jersey,"8,791,894","8,791,936","8,803,580","8,842,614","8,876,000","8,911,502","8,938,175"
.New Mexico,"2,059,179","2,059,192","2,064,950","2,078,407","2,084,594","2,086,895","2,085,572"
.New York,"19,378,102","19,378,112","19,400,867","19,521,745","19,607,140","19,695,680","19,746,227"
.North Carolina,"9,535,483","9,535,691","9,559,488","9,651,502","9,748,181","9,848,917","9,943,964"
.North Dakota,"672,591","672,591","674,345","685,242","701,705","723,857","739,482"
.Ohio,"11,536,504","11,536,725","11,540,070","11,544,757","11,550,901","11,572,005","11,594,163"
.Oklahoma,"3,751,351","3,751,616","3,759,481","3,786,527","3,817,059","3,853,118","3,878,051"
.Oregon,"3,831,074","3,831,073","3,837,083","3,867,644","3,898,684","3,928,068","3,970,239"
.Pennsylvania,"12,702,379","12,702,884","12,711,077","12,743,995","12,770,043","12,781,296","12,787,209"
.Rhode Island,"1,052,567","1,052,931","1,053,078","1,052,020","1,052,637","1,053,354","1,055,173"
.South Carolina,"4,625,364","4,625,401","4,636,290","4,673,054","4,722,621","4,771,929","4,832,482"
.South Dakota,"814,180","814,191","816,192","824,171","834,504","845,510","853,175"
.Tennessee,"6,346,105","6,346,275","6,356,628","6,398,389","6,455,177","6,497,269","6,549,352"
.Texas,"25,145,561","25,146,104","25,245,717","25,657,477","26,094,422","26,505,637","26,956,958"
.Utah,"2,763,885","2,763,885","2,774,346","2,815,324","2,855,194","2,902,787","2,942,902"
.Vermont,"625,741","625,745","625,792","626,450","626,138","626,855","626,562"
.Virginia,"8,001,024","8,001,023","8,025,376","8,110,188","8,193,422","8,270,345","8,326,289"
.Washington,"6,724,540","6,724,543","6,741,911","6,822,112","6,896,325","6,973,742","7,061,530"
.West Virginia,"1,852,994","1,853,033","1,854,176","1,854,982","1,856,313","1,853,595","1,850,326"
.Wisconsin,"5,686,986","5,687,289","5,689,268","5,708,785","5,724,888","5,742,953","5,757,564"
.Wyoming,"563,626","563,767","564,358","567,631","576,893","583,223","584,153"
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Puerto Rico,"3,725,789","3,726,157","3,721,527","3,686,771","3,642,281","3,595,839","3,548,397"
"Note: The estimates are based on the 2010 Census and reflect changes to the April 1, 2010 population due to the Count Question Resolution program and geographic program revisions. See Geographic Terms and Definitions at http://www.census.gov/popest/about/geo/terms.html for a list of the states that are included in each region. All geographic boundaries for the 2014 population estimates series are defined as of January 1, 2014. For population estimates methodology statements, see http://www.census.gov/popest/methodology/index.html.",NaN,NaN,NaN,NaN,NaN,NaN,NaN
Suggested Citation:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Table 1. Annual Estimates of the Resident Population for the United States, Regions, States, and Puerto Rico: April 1, 2010 to July 1, 2014 (NST-EST2014-01)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Source: U.S. Census Bureau, Population Division",NaN,NaN,NaN,NaN,NaN,NaN,NaN
Release Date: December 2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
pop_data.tail()

,Census,Estimates Base,2010,2011,2012,2013,2014
State,,,,,,,
"Note: The estimates are based on the 2010 Census and reflect changes to the April 1, 2010 population due to the Count Question Resolution program and geographic program revisions. See Geographic Terms and Definitions at http://www.census.gov/popest/about/geo/terms.html for a list of the states that are included in each region. All geographic boundaries for the 2014 population estimates series are defined as of January 1, 2014. For population estimates methodology statements, see http://www.census.gov/popest/methodology/index.html.",NaN,NaN,NaN,NaN,NaN,NaN,NaN
Suggested Citation:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Table 1. Annual Estimates of the Resident Population for the United States, Regions, States, and Puerto Rico: April 1, 2010 to July 1, 2014 (NST-EST2014-01)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Source: U.S. Census Bureau, Population Division",NaN,NaN,NaN,NaN,NaN,NaN,NaN
Release Date: December 2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
pop_data.dropna()

,Census,Estimates Base,2010,2011,2012,2013,2014
State,,,,,,,
United States,"308,745,538","308,758,105","309,347,057","311,721,632","314,112,078","316,497,531","318,857,056"
Northeast,"55,317,240","55,318,348","55,381,690","55,635,670","55,832,038","56,028,220","56,152,333"
Midwest,"66,927,001","66,929,898","66,972,390","67,149,657","67,331,458","67,567,871","67,745,108"
South,"114,555,744","114,562,951","114,871,231","116,089,908","117,346,322","118,522,802","119,771,934"
West,"71,945,553","71,946,908","72,121,746","72,846,397","73,602,260","74,378,638","75,187,681"
.Alabama,"4,779,736","4,780,127","4,785,822","4,801,695","4,817,484","4,833,996","4,849,377"
.Alaska,"710,231","710,249","713,856","722,572","731,081","737,259","736,732"
.Arizona,"6,392,017","6,392,310","6,411,999","6,472,867","6,556,236","6,634,997","6,731,484"
.Arkansas,"2,915,918","2,915,958","2,922,297","2,938,430","2,949,300","2,958,765","2,966,369"
.California,"37,253,956","37,254,503","37,336,011","37,701,901","38,062,780","38,431,393","38,802,500"
.Colorado,"5,029,196","5,029,324","5,048,575","5,119,661","5,191,709","5,272,086","5,355,866"
.Connecticut,"3,574,097","3,574,096","3,579,345","3,590,537","3,594,362","3,599,341","3,596,677"
.Delaware,"897,934","897,936","899,731","907,829","916,881","925,240","935,614"
.District of Columbia,"601,723","601,767","605,210","620,427","635,040","649,111","658,893"
.Florida,"18,801,310","18,804,623","18,852,220","19,107,900","19,355,257","19,600,311","19,893,297"
.Georgia,"9,687,653","9,688,681","9,714,464","9,813,201","9,919,000","9,994,759","10,097,343"
.Hawaii,"1,360,301","1,360,301","1,363,950","1,378,251","1,392,766","1,408,987","1,419,561"
.Idaho,"1,567,582","1,567,652","1,570,639","1,583,780","1,595,590","1,612,843","1,634,464"
.Illinois,"12,830,632","12,831,587","12,840,097","12,858,725","12,873,763","12,890,552","12,880,580"
.Indiana,"6,483,802","6,484,192","6,490,308","6,516,560","6,537,632","6,570,713","6,596,855"
.Iowa,"3,046,355","3,046,869","3,050,295","3,064,904","3,075,935","3,092,341","3,107,126"
.Kansas,"2,853,118","2,853,132","2,858,949","2,869,965","2,885,966","2,895,801","2,904,021"
.Kentucky,"4,339,367","4,339,349","4,349,838","4,370,038","4,383,465","4,399,583","4,413,457"
.Louisiana,"4,533,372","4,533,479","4,545,581","4,575,972","4,604,744","4,629,284","4,649,676"
.Maine,"1,328,361","1,328,361","1,327,361","1,327,930","1,328,592","1,328,702","1,330,089"
.Maryland,"5,773,552","5,773,785","5,788,101","5,843,833","5,891,819","5,938,737","5,976,407"
.Massachusetts,"6,547,629","6,547,817","6,564,073","6,612,270","6,655,829","6,708,874","6,745,408"
.Michigan,"9,883,640","9,884,133","9,876,498","9,875,736","9,884,781","9,898,193","9,909,877"
.Minnesota,"5,303,925","5,303,925","5,310,418","5,348,036","5,380,615","5,422,060","5,457,173"
.Mississippi,"2,967,297","2,968,103","2,970,811","2,978,464","2,986,137","2,992,206","2,994,079"
.Missouri,"5,988,927","5,988,923","5,996,085","6,010,544","6,025,281","6,044,917","6,063,589"
.Montana,"989,415","989,417","990,575","997,661","1,005,163","1,014,864","1,023,579"
.Nebraska,"1,826,341","1,826,341","1,829,865","1,842,232","1,855,487","1,868,969","1,881,503"
.Nevada,"2,700,551","2,700,692","2,703,493","2,718,586","2,755,245","2,791,494","2,839,099"
.New Hampshire,"1,316,470","1,316,466","1,316,517","1,318,109","1,321,297","1,322,616","1,326,813"
.New Jersey,"8,791,894","8,791,936","8,803,580","8,842,614","8,876,000","8,911,502","8,938,175"
.New Mexico,"2,059,179","2,059,192","2,064,950","2,078,407","2,084,594","2,086,895","2,085,572"
.New York,"19,378,102","19,378,112","19,400,867","19,521,745","19,607,140","19,695,680","19,746,227"
.North Carolina,"9,535,483","9,535,691","9,559,488","9,651,502","9,748,181","9,848,917","9,943,964"
.North Dakota,"672,591","672,591","674,345","685,242","701,705","723,857","739,482"
.Ohio,"11,536,504","11,536,725","11,540,070","11,544,757","11,550,901","11,572,005","11,594,163"
.Oklahoma,"3,751,351","3,751,616","3,759,481","3,786,527","3,817,059","3,853,118","3,878,051"
.Oregon,"3,831,074","3,831,073","3,837,083","3,867,644","3,898,684","3,928,068","3,970,239"
.Pennsylvania,"12,702,379","12,702,884","12,711,077","12,743,995","12,770,043","12,781,296","12,787,209"
.Rhode Island,"1,052,567","1,052,931","1,053,078","1,052,020","1,052,637","1,053,354","1,055,173"
.South Carolina,"4,625,364","4,625,401","4,636,290","4,673,054","4,722,621","4,771,929","4,832,482"
.South Dakota,"814,180","814,191","816,192","824,171","834,504","845,510","853,175"
.Tennessee,"6,346,105","6,346,275","6,356,628","6,398,389","6,455,177","6,497,269","6,549,352"
.Texas,"25,145,561","25,146,104","25,245,717","25,657,477","26,094,422","26,505,637","26,956,958"
.Utah,"2,763,885","2,763,885","2,774,346","2,815,324","2,855,194","2,902,787","2,942,902"
.Vermont,"625,741","625,745","625,792","626,450","626,138","626,855","626,562"
.Virginia,"8,001,024","8,001,023","8,025,376","8,110,188","8,193,422","8,270,345","8,326,289"
.Washington,"6,724,540","6,724,543","6,741,911","6,822,112","6,896,325","6,973,742","7,061,530"
.West Virginia,"1,852,994","1,853,033","1,854,176","1,854,982","1,856,313","1,853,595","1,850,326"
.Wisconsin,"5,686,986","5,687,289","5,689,268","5,708,785","5,724,888","5,742,953","5,757,564"
.Wyoming,"563,626","563,767","564,358","567,631","576,893","583,223","584,153"
Puerto Rico,"3,725,789","3,726,157","3,721,527","3,686,771","3,642,281","3,595,839","3,548,397"

In [80]:
pop_data = pop_data.dropna()

In [81]:
pop_data.index

Index(['United States', 'Northeast', 'Midwest', 'South', 'West', '.Alabama',
       '.Alaska', '.Arizona', '.Arkansas', '.California', '.Colorado',
       '.Connecticut', '.Delaware', '.District of Columbia', '.Florida',
       '.Georgia', '.Hawaii', '.Idaho', '.Illinois', '.Indiana', '.Iowa',
       '.Kansas', '.Kentucky', '.Louisiana', '.Maine', '.Maryland',
       '.Massachusetts', '.Michigan', '.Minnesota', '.Mississippi',
       '.Missouri', '.Montana', '.Nebraska', '.Nevada', '.New Hampshire',
       '.New Jersey', '.New Mexico', '.New York', '.North Carolina',
       '.North Dakota', '.Ohio', '.Oklahoma', '.Oregon', '.Pennsylvania',
       '.Rhode Island', '.South Carolina', '.South Dakota', '.Tennessee',
       '.Texas', '.Utah', '.Vermont', '.Virginia', '.Washington',
       '.West Virginia', '.Wisconsin', '.Wyoming', 'Puerto Rico'],
      dtype='object', name='State')

In [82]:
pop_data.index = pop_data.index.to_series().map(lambda state: re.sub(r"^\.", "", state))

# Equivalent lines
# pop_data.index = pop_data.index.to_series().str.replace(r"^\.", "")
# state_names = pop_data.index.to_series()
# state_names.map(lambda name: name[1:] if name.startswith(".") else name)

In [83]:
pop_data.head(10)

,Census,Estimates Base,2010,2011,2012,2013,2014
State,,,,,,,
United States,"308,745,538","308,758,105","309,347,057","311,721,632","314,112,078","316,497,531","318,857,056"
Northeast,"55,317,240","55,318,348","55,381,690","55,635,670","55,832,038","56,028,220","56,152,333"
Midwest,"66,927,001","66,929,898","66,972,390","67,149,657","67,331,458","67,567,871","67,745,108"
South,"114,555,744","114,562,951","114,871,231","116,089,908","117,346,322","118,522,802","119,771,934"
West,"71,945,553","71,946,908","72,121,746","72,846,397","73,602,260","74,378,638","75,187,681"
Alabama,"4,779,736","4,780,127","4,785,822","4,801,695","4,817,484","4,833,996","4,849,377"
Alaska,"710,231","710,249","713,856","722,572","731,081","737,259","736,732"
Arizona,"6,392,017","6,392,310","6,411,999","6,472,867","6,556,236","6,634,997","6,731,484"
Arkansas,"2,915,918","2,915,958","2,922,297","2,938,430","2,949,300","2,958,765","2,966,369"
California,"37,253,956","37,254,503","37,336,011","37,701,901","38,062,780","38,431,393","38,802,500"

In [84]:
# int("1,000") will not work

In [85]:
import locale

In [86]:
help(locale.atoi)

Help on function atoi in module locale:

atoi(str)
    Converts a string to an integer according to the locale settings.

In [87]:
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8') 
locale.atoi("1,000")

1000

In [88]:
pop_data.applymap(locale.atoi).head()

,Census,Estimates Base,2010,2011,2012,2013,2014
State,,,,,,,
United States,308745538,308758105,309347057,311721632,314112078,316497531,318857056
Northeast,55317240,55318348,55381690,55635670,55832038,56028220,56152333
Midwest,66927001,66929898,66972390,67149657,67331458,67567871,67745108
South,114555744,114562951,114871231,116089908,117346322,118522802,119771934
West,71945553,71946908,72121746,72846397,73602260,74378638,75187681

In [89]:
help(pop_data.applymap)

Help on method applymap in module pandas.core.frame:

applymap(func) method of pandas.core.frame.DataFrame instance
    Apply a function to a DataFrame that is intended to operate
    elementwise, i.e. like doing map(func, series) for each series in the
    DataFrame

    Parameters
    ----------
    func : function
        Python function, returns a single value from a single value

    Returns
    -------
    applied : DataFrame

    See also
    --------
    DataFrame.apply : For operations on rows/columns

In [90]:
pop_data.head()

,Census,Estimates Base,2010,2011,2012,2013,2014
State,,,,,,,
United States,"308,745,538","308,758,105","309,347,057","311,721,632","314,112,078","316,497,531","318,857,056"
Northeast,"55,317,240","55,318,348","55,381,690","55,635,670","55,832,038","56,028,220","56,152,333"
Midwest,"66,927,001","66,929,898","66,972,390","67,149,657","67,331,458","67,567,871","67,745,108"
South,"114,555,744","114,562,951","114,871,231","116,089,908","117,346,322","118,522,802","119,771,934"
West,"71,945,553","71,946,908","72,121,746","72,846,397","73,602,260","74,378,638","75,187,681"

In [91]:
pop_data = pop_data.applymap(locale.atoi)

In [92]:
pop_data.head()

,Census,Estimates Base,2010,2011,2012,2013,2014
State,,,,,,,
United States,308745538,308758105,309347057,311721632,314112078,316497531,318857056
Northeast,55317240,55318348,55381690,55635670,55832038,56028220,56152333
Midwest,66927001,66929898,66972390,67149657,67331458,67567871,67745108
South,114555744,114562951,114871231,116089908,117346322,118522802,119771934
West,71945553,71946908,72121746,72846397,73602260,74378638,75187681

In [93]:
states = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}

states = {name: abbr for abbr, name in states.items()}

In [94]:
pop_data.index.to_series().map(states)

State
United States           NaN
Northeast               NaN
Midwest                 NaN
South                   NaN
West                    NaN
Alabama                  AL
Alaska                   AK
Arizona                  AZ
Arkansas                 AR
California               CA
Colorado                 CO
Connecticut              CT
Delaware                 DE
District of Columbia     DC
Florida                  FL
Georgia                  GA
Hawaii                   HI
Idaho                    ID
Illinois                 IL
Indiana                  IN
Iowa                     IA
Kansas                   KS
Kentucky                 KY
Louisiana                LA
Maine                    ME
Maryland                 MD
Massachusetts            MA
Michigan                 MI
Minnesota                MN
Mississippi              MS
Missouri                 MO
Montana                  MT
Nebraska                 NE
Nevada                   NV
New Hampshire            NH
New Jersey               NJ
New Mexico               NM
New York                 NY
North Carolina           NC
North Dakota             ND
Ohio                     OH
Oklahoma                 OK
Oregon                   OR
Pennsylvania             PA
Rhode Island             RI
South Carolina           SC
South Dakota             SD
Tennessee                TN
Texas                    TX
Utah                     UT
Vermont                  VT
Virginia                 VA
Washington               WA
West Virginia            WV
Wisconsin                WI
Wyoming                  WY
Puerto Rico              PR
Name: State, dtype: object

In [95]:
states = pd.Series(states)

In [96]:
states.to_frame()

                           0
Alabama                   AL
Alaska                    AK
American Samoa            AS
Arizona                   AZ
Arkansas                  AR
California                CA
Colorado                  CO
Connecticut               CT
Delaware                  DE
District of Columbia      DC
Florida                   FL
Georgia                   GA
Guam                      GU
Hawaii                    HI
Idaho                     ID
Illinois                  IL
Indiana                   IN
Iowa                      IA
Kansas                    KS
Kentucky                  KY
Louisiana                 LA
Maine                     ME
Maryland                  MD
Massachusetts             MA
Michigan                  MI
Minnesota                 MN
Mississippi               MS
Missouri                  MO
Montana                   MT
National                  NA
Nebraska                  NE
Nevada                    NV
New Hampshire             NH
New Jersey                NJ
New Mexico                NM
New York                  NY
North Carolina            NC
North Dakota              ND
Northern Mariana Islands  MP
Ohio                      OH
Oklahoma                  OK
Oregon                    OR
Pennsylvania              PA
Puerto Rico               PR
Rhode Island              RI
South Carolina            SC
South Dakota              SD
Tennessee                 TN
Texas                     TX
Utah                      UT
Vermont                   VT
Virgin Islands            VI
Virginia                  VA
Washington                WA
West Virginia             WV
Wisconsin                 WI
Wyoming                   WY

In [100]:
pop_data = pop_data.join(states.to_frame(name="Abbr"), how="inner")
# Equivalent to:
# pop_data = pop_data.merge(states.to_frame(name="Abbr"), left_index=True, right_index=True, how="inner")

In [101]:
pop_data.index = pop_data['Abbr']

In [102]:
pop_data.head()

,Census,Estimates Base,2010,2011,2012,2013,2014,Abbr
Abbr,,,,,,,,
AL,4779736,4780127,4785822,4801695,4817484,4833996,4849377,AL
AK,710231,710249,713856,722572,731081,737259,736732,AK
AZ,6392017,6392310,6411999,6472867,6556236,6634997,6731484,AZ
AR,2915918,2915958,2922297,2938430,2949300,2958765,2966369,AR
CA,37253956,37254503,37336011,37701901,38062780,38431393,38802500,CA